  0%|                                                                                                                                                                                                                                                                                                        | 0/1 [00:00<?, ?it/s]/home/icl2/anaconda3/lib/python3.10/site-packages/torch/cuda/memory.py:330: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
  warnings.warn(
0, 0.13643696904182434, 0.14447660744190216
1, 0.13643696904182434, 0.13965079188346863
2, 0.13309574127197266, 0.12999913096427917
3, 0.12652230262756348, 0.11553279310464859
4, 0.11695121973752975, 0.09627227485179901
5, 0.10477723926305771, 0.07226990163326263
6, 0.09059017896652222, 0.043655700981616974
7, 0.075203537940979, 0.01069234125316143
8, 0.05963701754808426, -0.026130832731723785
9, 0.04504495859146118, -0.06597363948822021
10, 0.03254442662000656, -0.10756547749042511
11, 0.02296275459229946, -0.14545926451683044
12, 0.01703879050910473, -0.1788981407880783
13, 0.013744255527853966, -0.20750603079795837
14, 0.012128835543990135, -0.2312467247247696
15, 0.011450566351413727, -0.2503177523612976
16, 0.01120476983487606, -0.2650529146194458
  0%|                                                                                                                                                                                                                                                                                                        | 0/1 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "/home/icl2/khlee/InstaFlow/code/main_new_algorithm.py", line 241, in <module>
    main()
  File "/home/icl2/khlee/InstaFlow/code/main_new_algorithm.py", line 180, in main
    original_image, recon_image, diff_image, original_latents_visualized, recon_latents_visualized, diff_latents_visualized, error_TOT, error_OTO, error_middle, output_loss, peak_gpu_allocated, inf_time, inv_time, seed = single_exp(seed, prompt, inversion_prompt,
  File "/home/icl2/anaconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/icl2/khlee/InstaFlow/code/main_new_algorithm.py", line 47, in single_exp
    recon_images, recon_zo, recon_latents, output_loss, peak_gpu_allocated, dec_inv_time = insta_pipe.exact_inversion(
  File "/home/icl2/khlee/InstaFlow/code/pipeline_rf.py", line 937, in exact_inversion
    latents = self.edcorrector(image, decoder_inv_steps=decoder_inv_steps, decoder_lr=decoder_lr, verbose=verbose)
  File "/home/icl2/khlee/InstaFlow/code/pipeline_rf.py", line 1302, in edcorrector
    print(f"{i}, {loss.item()}, {z.mean().item()}")
KeyboardInterrupt
17, 0.01108271162956953, -0.27585557103157043
18, 0.010918330401182175, -0.28315770626068115